cc_test(
    name = "main",
    srcs = ["example.cpp"],
    deps = [
        # Add internal deps here, e.g. `//src:XXX`.
        "@gtest//:gtest",
        "@gtest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

